dataSources:
  - name: train
    type: local-csv
    path: train.csv.gz
    compression: gzip
    sampleSize: 2000

  - name: test
    type: local-csv
    path: train.csv.gz
    compression: gzip
    sampleSize: 400

  - name: labels
    type: local-labels-txt
    path: labels.txt

models:
  - name: p2p-tags-v2
    type: nlp-st # https://simpletransformers.ai/
    variant: distilbert
    task: nlp
    label: single
    params:
      # EVAL
      evaluate_during_training: True
      evaluate_during_training_verbose: True
      evaluate_during_training_steps: 1000
      # SAVE
      save_steps: -1
      save_eval_checkpoints: False
      save_model_every_epoch: False
      save_optimizer_and_scheduler: False
      # TRAINING:
      num_train_epochs: 1

pipelines:
  - name: p2p-tags-v2
    artifactsPath: ./target
    train:
      model: p2p-tags-v2
      trainDataSource: train
      testDataSource: test
      labelsDataSource: labels

